[profile.default]
src = 'src'
out = 'out'
test = 'test'
libs = ["lib"]
script = "script"
sizes = true
verbosity = 3
rpc_storage_caching = { chains = "all", endpoints = "all" }
solc = "0.8.18"
optimizer = true
optimizer_runs = 200
gas_reports = ["StakingDiamond"]
ffi = true
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/=lib/openzeppelin-contracts/contracts/',
    'solidity-stringutils/=lib/solidity-stringutils/',
]

[fmt]
line_length = 120
wrap_comments = true
quote_style = "double"
tab_width = 4

[fuzz]
runs = 128

[invariant]
runs = 128
depth = 128
fail_on_revert = true

[profile.ci]
verbosity = 1

[profile.ci.invariant]
runs = 64
depth = 64
fail_on_revert = true

[profile.ci.fuzz]
runs = 64
